name: fosskers
version: '1.0.0'
synopsis: My personal site.
description: My personal site.
category: Web
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3
git: git://github.com/fosskers/fosskers.ca.git

extra-source-files:
  - README.org

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.8 && < 4.11
  - text >= 1.2 && < 1.3

library:
  source-dirs: lib

executables:
  site:
    source-dirs: site
    main: Site.hs
    dependencies:
      - fosskers
      - miso >= 0.10 && < 0.13

  server:
    source-dirs: server
    main: Server.hs
    dependencies:
      - fosskers
      - servant >= 0.11 && < 0.13
      - servant-server >= 0.11 && < 0.13
