resolver: lts-11.0

packages:
  - lib
  - server
  - bridge

extra-deps:
  - html-entities-1.1.4.2
  - servant-xml-1.0.1.1
  - xmlbf-0.3
  - xmlbf-xeno-0.1.1
  - git: https://github.com/fosskers/kanji
    commit: a739d4bf367d7af7c4d883e6dd3f6c68d1812bd8
