resolver: lts-16.31

ghc-options:
  $everything: -split-sections
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-1.1.1
  - org-mode-lucid-1.6.0
  - skylighting-lucid-1.0.0
  - xmlbf-0.6.1
