resolver: lts-15.3

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-1.0.0
  - org-mode-lucid-1.1.0
  - servant-xml-1.0.1.4
  - skylighting-lucid-1.0.0
  - xmlbf-0.6.1
  - xmlbf-xeno-0.2
