resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Forced Upgrades --- #
  - megaparsec-8.0.0
  - parser-combinators-1.2.1
  - shelly-1.9.0
  # --- Raw --- #
  - github: fosskers/org-mode
    commit: e05bfe536ac456fadd09771659740b03b6496af5
    subdirs:
      - org-mode
      - org-mode-lucid
