resolver: lts-19.7

ghc-options:
  $everything: -split-sections
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

flags:
  these:
    assoc: false
  strict:
    assoc: false

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-2.0.1
  - org-mode-lucid-1.6.2
  - skylighting-lucid-1.0.2
  - xmlbf-0.6.1
