resolver: lts-15.4

ghc-options: {"$locals": -fwrite-ide-info}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-1.1.0
  # - org-mode-lucid-1.2.0
  - servant-xml-1.0.1.4
  - skylighting-lucid-1.0.0
  - xmlbf-0.6.1
  - xmlbf-xeno-0.2
  - github: fosskers/org-mode
    commit: 9efc5fdf0b9bd50751dd76057a04281809496bdc
    subdirs:
      - org-mode-lucid
