resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Forced Upgrades --- #
  - megaparsec-8.0.0
  - parser-combinators-1.2.1
  - shelly-1.9.0
  # --- Raw --- #
  - github: fosskers/org-mode
    commit: 2f47bc7cf151fa7c0bf6991a52d0488dab14e912
    subdirs:
      - org-mode
      - org-mode-lucid
