resolver: lts-15.2

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-1.0.0
  # - org-mode-lucid-1.0.1
  - servant-xml-1.0.1.4
  - xmlbf-0.6.1
  - xmlbf-xeno-0.2
  - github: fosskers/org-mode
    commit: b4baa42d6e81ba706cf78b1992721380c10785a0
    subdirs:
      - org-mode-lucid
  - github: fosskers/skylighting-lucid
    commit: a440b1b98aeba219dba03ad7dad67772e6fef660
