resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Forced Upgrades --- #
  - shelly-1.9.0
  # --- Raw --- #
  - github: fosskers/org-mode
    commit: 192a62e54828e316dfb054ea081e32856a6eb6c8
    subdirs:
      - org-mode
      - org-mode-lucid
