resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

flags:
  these:
    aeson: false
    assoc: false
    semigroupoids: false
    QuickCheck: false

extra-deps:
  # --- Forced Upgrades --- #
  - megaparsec-8.0.0
  - parser-combinators-1.2.1
  - shelly-1.9.0
  # --- Raw --- #
  - github: fosskers/org-mode
    commit: 73c8ea132d7d1ae288df22fd1974c938e2444fa8
    subdirs:
      - org-mode
      - org-mode-lucid
