resolver: lts-11.1

packages:
  - lib
  - server
  - bridge

extra-deps:
  - html-entities-1.1.4.2
  - purescript-bridge-0.12.0.0
  - servant-xml-1.0.1.1
  - xmlbf-0.3
  - xmlbf-xeno-0.1.1
  - git: https://github.com/fosskers/kanji
    commit: 2f9e7b4eec768e688c27a52985f3e7217d987abc
