resolver: lts-22.24

ghc-options:
  $everything: -split-sections
  $locals: -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-2.1.0
  - org-mode-lucid-1.7.0
  - skylighting-lucid-1.0.4
