resolver: lts-16.2

ghc-options: {"$locals": -fwrite-ide-info -hiedir=.hie -fmax-relevant-binds=0}

extra-deps:
  # --- Missing from Stackage --- #
  - org-mode-1.1.0
  - org-mode-lucid-1.4.0
  - skylighting-lucid-1.0.0
  - xmlbf-0.6.1
