name: server
version: '1.0.0'
synopsis: My personal site.
description: My personal site.
category: Web
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3
git: git://github.com/fosskers/fosskers.ca.git

extra-source-files:
  - ../blog/*.org

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.8 && < 4.11
  - aeson >= 1.2 && < 1.3
  - containers
  - protolude >= 0.2 && < 0.3
  - text >= 1.2 && < 1.3
  - unordered-containers

executables:
  server:
    source-dirs: .
    main: Server.hs
    dependencies:
      - fosskers
      - blaze-html >= 0.9 && < 0.10
      - data-default >= 0.7 && < 0.8
      - lens >= 4.15 && < 4.17
      - lucid >= 2.9 && < 2.10
      - natural-transformation >= 0.4 && < 0.5
      - optparse-generic >= 1.2 && < 1.3
      - pandoc >= 2.0 && < 2.1
      - servant >= 0.11 && < 0.13
      - servant-server >= 0.11 && < 0.13
      - shelly >= 1.7 && < 1.8
      - system-filepath
      - warp >= 3.2 && < 3.3
