#+TITLE: Resources for Functional Programming
#+DATE: 2018-02-20
#+AUTHOR: Colin
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../assets/org-theme.css"/>

* Languages

** Haskell

- [[https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/][An Opinionated Guide to Haskell in 2018]]

#+BEGIN_QUOTE
I have never been in a community of programmers so dedicated and passionate
about applying thought and rigor to building software, then going out and
actually doing it.

...

One of my primary motivators for writing Haskell is that it is fun and it
challenges me intellectually in ways that other languages don’t. But that
challenge is not a sign of uselessness, it is a sign that Haskell is so close
to letting me do the right thing, to solving the problem the right way, to
letting me work without compromises.
When I write in most programming languages, I must constantly accept that
my program will never be robust in all the ways I want it to be, and I
might as well give up before I even start. Haskell’s greatest weakness
is that it tempts me to try.
#+END_QUOTE

- [[https://blog.jle.im/entry/introducing-the-backprop-library.html][backprop]] library announcement

** Purescript

- [[https://www.youtube.com/watch?v=HLEwYghBjo8][Lessons Learned using Purescript to build Mobile Apps Dev Framework]]
- http://mutanatum.com/posts/2017-01-12-Browser-FP-Head-to-Head.html

** Scala

- (2015) [[https://gist.github.com/djspiewak/2ae2570c8856037a7738][Collections Redesign Proposal]]

* Documentation

- [[https://www.divio.com/en/blog/documentation/][What Nobody Tells You About Documentation]]

* Books

- [[https://leanpub.com/outsidefp][An Outsider's Guide to Statically Typed FP]]
