#+TITLE: The Henro Pilgrimage
#+DATE: 2024-06-04
#+AUTHOR: Colin
#+CATEGORY: buddhism

From 2024 April 16th to June 1st I walked 1265 kilometers around the island of
Shikoku in Japan. The route is called the [[https://en.wikipedia.org/wiki/Shikoku_Pilgrimage][Henro Pilgrimage]] and has existed in
evolving forms for perhaps 800 years. It is based on [[https://en.wikipedia.org/wiki/Shingon_Buddhism][Shingon Buddhism]] and
involves visiting 88 temples, offering rites and receiving various marks of
passage.

The route took me 47 days, the last of which I spent climbing Koyasan in
Wakayama to report my success to [[https://en.wikipedia.org/wiki/K%C5%ABkai][Kūkai]], the monk who brought Shingon to Japan
from China in the 800s, and is said to be in a state of eternal meditation on
the mountaintop.

This article is a transcription and translation of my handwritten journal
entries.

* Tokushima Prefecture - The Beginning

** Day 0

Apparently the Japanese word for "Leech" is "Hiru", which happens to overlap
with the word for "afternoon". I've already been to Temple 1, Ryōzenji, with
Takahara-san, an 80-year-old man that is staying at the same Henro House lodge
as me today. I've already bought all the gear I need except for a [[https://en.wikipedia.org/wiki/Kasa_(hat)][Sugegasa]]. My
official start is supposed to be tomorrow, but the guy running the lodge
suggested we get the first temple out of the way today (just 100m up the road)
so that we can get on our way earlier tomorrow. We took his advice but it was
still so sudden that a large part of me was having trouble believing the journey
had really begun. Tonight I'm sharing a room with Takahara-san.

Post-trip Addendum:

[[https://henrohouse.jp/en][Henro House]] is an alliance of inns that cater to walking pilgrims and
smartphone-savvy folks from overseas. You can check availability and book
directly online. Average cost for one night is around 3500 yen. Sometimes they
feed you but not always.

I say "shared a room" but it was massive and probably could have slept 10
people.

Original Japanese:

「蛭」は Leech らしい。遍路ハウスで知り合った高原さん（８０歳）と一緒に霊山寺に
お詣りした。菅笠以外は全部購入済み。正式な出発は明日のはずだったが宿の人に今日の
内にした方が朝早く旅立てると言われてそうしたけれど、急で気持ちが追いつかなかった。
夜は高原さんと相部屋。
