#+TITLE: The Henro Pilgrimage
#+DATE: 2024-06-04
#+AUTHOR: Colin
#+CATEGORY: buddhism

From 2024 April 16th to June 1st I walked 1265 kilometers around the island of
Shikoku in Japan. The route is called the [[https://en.wikipedia.org/wiki/Shikoku_Pilgrimage][Henro Pilgrimage]] and has existed in
evolving forms for perhaps 800 years. It is based on [[https://en.wikipedia.org/wiki/Shingon_Buddhism][Shingon Buddhism]] and
involves visiting 88 temples, offering rites and receiving various marks of
passage.

The route took me 47 days, the last of which I spent climbing Koyasan in
Wakayama to report my success to [[https://en.wikipedia.org/wiki/K%C5%ABkai][Kūkai]], the monk who brought Shingon to Japan
from China in the 800s, and is said to be in a state of eternal meditation on
the mountaintop.

This article is a transcription and translation of my handwritten journal
entries.

* Tokushima Prefecture - The Beginning

** Day 0 - April 15

Apparently the Japanese word for "Leech" is "Hiru", which happens to overlap
with the word for "afternoon". I've already been to Temple 1, Ryōzenji, with
Takahara-san, an 80-year-old man that is staying at the same Henro House lodge
as me today. I've already bought all the gear I need except for a [[https://en.wikipedia.org/wiki/Kasa_(hat)][Sugegasa]]. My
official start is supposed to be tomorrow, but the guy running the lodge
suggested we get the first temple out of the way today (just 100m up the road)
so that we can get on our way earlier tomorrow. We took his advice but it was
still so sudden that a large part of me was having trouble believing the journey
had really begun. Tonight I'm sharing a room with Takahara-san.

Post-trip Addendum:

[[https://henrohouse.jp/en][Henro House]] is an alliance of inns that cater to walking pilgrims and
smartphone-savvy folks from overseas. You can check availability and book
directly online. Average cost for one night is around 3500 yen. Sometimes they
feed you but not always.

I say "shared a room" but it was massive and probably could have slept 10
people.

Original Japanese:

「蛭」は Leech らしい。遍路ハウスで知り合った高原さん（８０歳）と一緒に霊山寺に
お詣りした。菅笠以外は全部購入済み。正式な出発は明日のはずだったが宿の人に今日の
内にした方が朝早く旅立てると言われてそうしたけれど、急で気持ちが追いつかなかった。
夜は高原さんと相部屋。

** Day 1 - April 16

I couldn't sleep until past midnight. Nerves and other thoughts swam through my
head. I was worried that my [[https://en.wikipedia.org/wiki/Kong%C5%8D-zue][Kongō Staff]] wouldn't last the trip, but I see now
that it's pretty much the same as everyone else has.

Breakfast was offered as /Osettai/ by the Henro House. After setting off I headed
up to [[https://en.wikipedia.org/wiki/%C5%8Casahiko_Shrine][Ōasa-Hiko Jinja]] to ask protection from the nature gods (even though this
is a Buddhist pilgrimage). It was 7 a.m. but there was already an attendent
around. He was quite nice and sold me a charm unique to their Shrine made of
hemp. Setting off again, I cried for some reason. I felt like I had a lot of
support behind me and felt new determination.

Gokurakuji (2) was quite beautiful, and I couldn't shake the feeling I had been
to Kinsenji (3) already last year. At Dainichiji (4) I gave some candies to a
pair of older pilgrims. As I was taking a break, I met a guy named Jeffery from
Taiwan, but I was concerned that Takahara-san hadn't shown up yet. It was noon
by the time I arrived at Jizōji (5), so I bought a bentō from a lady selling
them in the parking lot. At Anrakuji (6) I ran into Jeffery again and we
discussed where we'd be sleeping for the night. I got us permission to stay in
the bell tower above the main gate from the temple staff. First though he'd head
up the road to Jūrakuji (7) and do it early. While there I met an American girl
from Hawaii named Sydney. She was pretty cute. She had nowhere to stay that
night so I took out my Japanese map and showed her the location of an offical
Henro Hut nearby. I'll probably see her again.

Once back at Anrakuji, lo-and-behold, Takahara-san was standing at the entrance.
Apparently he had gotten quite lost in the afternoon, but was otherwise fine. He
soon set off for the next temple. We then found someone else in the Bell Tower,
a tatami maker from Kyōto named Kenji-san. It's the three of us here tonight.

Osettai: Breakfast, candles, incense, a handle cover for my staff, eggs and
water, chocolate.

Post-trip Addendum:

/Osettai/ is a pilgrim hospitality culture specific to Shikoku. The locals know
how hard the journey is, so they offer whatever help they can, often in the form
of food or drinks.

I came with a tent packed for days that I'd sleep outside. I hoped for about a
50/50 split between that and staying in inns. When you're walking the pilgrimage
route it's basically impossible to plan ahead of time (re: reservations), since
you don't know how far you'll get each day. There's a lot of playing it by ear.

Temples generally don't close their gates, but the temple offices where you
receive proof of passage open at 8 a.m. So no matter how quickly you arrive
there in the morning, you can't continue until past 8. Hence it's part of a
walker's strategy to position the previous night's lodging about 2 hours away
from the next temple. You start walking at 6, get there just before 8, do the
rites, and you're on your way with no time loss.

Original Japanese:

不安と考え事で零時過ぎまで寝れなかった。金剛杖の丈夫さの心配もあったが朝起きて改
めて見ると他の人のとさほど変わらん。

朝食はお接待で遍路ハウスで頂いた。出発したらまず大麻比古神社に寄った。朝の七時で
も管理の人が優しく麻でできたお守を売ってくれた。なぜか泣いた。

極楽寺は綺麗だった。金泉寺は来た事がある気がしてならんかった。大日寺で二人のおじ
さんに飴を上げた。待っていると、台湾の Jeffery が現れても高原さんが中々来ず心配
した。地蔵寺で丁度お昼になってお弁当を売っているおばさんから買って食べた。安楽寺
まで行くとまた Jeffery と鉢合わせして今夜の野宿計画を立てた。まず十楽寺まで行っ
てお詣りしていると、ハワイ在住のアメリカ人女性と話した。 Pretty cute だった。宿
坊の予約がなかったから地図を見せて先の遍路小屋に送った。また会うだろう。夜は六番
の山門の上の鐘楼で寝る。戻ったら奇跡的に高原さんも居て、昼はさんざん迷ったと言う。
鐘楼にもう一人先客の「けんじさん」も居る。

お接待：朝食・蝋燭・線香・金剛杖の帽子・卵と水・チョコ
