#+TITLE: The Henro Pilgrimage
#+DATE: 2024-06-04
#+AUTHOR: Colin
#+CATEGORY: buddhism

From 2024 April 16th to June 1st I walked 1265 kilometers around the island of
Shikoku in Japan. The route is called the [[https://en.wikipedia.org/wiki/Shikoku_Pilgrimage][Henro Pilgrimage]] and has existed in
evolving forms for perhaps 800 years. It is based on [[https://en.wikipedia.org/wiki/Shingon_Buddhism][Shingon Buddhism]] and
involves visiting 88 temples, offering rites and receiving various marks of
passage.

The route took me 47 days, the last of which I spent climbing Koyasan in
Wakayama to report my success to [[https://en.wikipedia.org/wiki/K%C5%ABkai][Kūkai]], the monk who brought Shingon to Japan
from China in the 800s, and is said to be in a state of eternal meditation on
the mountaintop.

This article is a transcription and translation of my handwritten journal
entries.

* Tokushima Prefecture - The Beginning

** Day 0 - April 15

Apparently the Japanese word for "Leech" is "Hiru", which happens to overlap
with the word for "afternoon". I've already been to Temple 1, Ryōzenji, with
Takahara-san, an 80-year-old man that is staying at the same Henro House lodge
as me today. I've already bought all the gear I need except for a [[https://en.wikipedia.org/wiki/Kasa_(hat)][Sugegasa]]. My
official start is supposed to be tomorrow, but the guy running the lodge
suggested we get the first temple out of the way today (just 100m up the road)
so that we can get on our way earlier tomorrow. We took his advice but it was
still so sudden that a large part of me was having trouble believing the journey
had really begun. Tonight I'm sharing a room with Takahara-san.

Post-trip Addendum:

[[https://henrohouse.jp/en][Henro House]] is an alliance of inns that cater to walking pilgrims and
smartphone-savvy folks from overseas. You can check availability and book
directly online. Average cost for one night is around 3500 yen. Sometimes they
feed you but not always.

I say "shared a room" but it was massive and probably could have slept 10
people.

Original Japanese:

「蛭」は Leech らしい。遍路ハウスで知り合った高原さん（８０歳）と一緒に霊山寺に
お詣りした。菅笠以外は全部購入済み。正式な出発は明日のはずだったが宿の人に今日の
内にした方が朝早く旅立てると言われてそうしたけれど、急で気持ちが追いつかなかった。
夜は高原さんと相部屋。

** Day 1 - April 16 (19km)

I couldn't sleep until past midnight. Nerves and other thoughts swam through my
head. I was worried that my [[https://en.wikipedia.org/wiki/Kong%C5%8D-zue][Kongō Staff]] wouldn't last the trip, but I see now
that it's pretty much the same as everyone else has.

Breakfast was offered as /Osettai/ by the Henro House. After setting off I headed
up to [[https://en.wikipedia.org/wiki/%C5%8Casahiko_Shrine][Ōasa-Hiko Jinja]] to ask protection from the nature gods (even though this
is a Buddhist pilgrimage). It was 7 a.m. but there was already an attendent
around. He was quite nice and sold me a charm unique to their Shrine made of
hemp. Setting off again, I cried for some reason. I felt like I had a lot of
support behind me and felt new determination.

Gokurakuji (2) was quite beautiful, and I couldn't shake the feeling I had been
to Kinsenji (3) already last year. At Dainichiji (4) I gave some candies to a
pair of older pilgrims. As I was taking a break, I met a guy named Jeffery from
Taiwan, but I was concerned that Takahara-san hadn't shown up yet. It was noon
by the time I arrived at Jizōji (5), so I bought a bentō from a lady selling
them in the parking lot. At Anrakuji (6) I ran into Jeffery again and we
discussed where we'd be sleeping for the night. I got us permission to stay in
the bell tower above the main gate from the temple staff. First though he'd head
up the road to Jūrakuji (7) and do it early. While there I met an American girl
from Hawaii named Sydney. She was pretty cute. She had nowhere to stay that
night so I took out my Japanese map and showed her the location of an offical
Henro Hut nearby. I'll probably see her again.

Once back at Anrakuji, lo-and-behold, Takahara-san was standing at the entrance.
Apparently he had gotten quite lost in the afternoon, but was otherwise fine. He
soon set off for the next temple. We then found someone else in the Bell Tower,
a tatami maker from Kyōto named Kenji-san. It's the three of us here tonight.

Osettai: Breakfast, candles, incense, a handle cover for my staff, eggs and
water, chocolate.

Post-trip Addendum:

/Osettai/ is a pilgrim hospitality culture specific to Shikoku. The locals know
how hard the journey is, so they offer whatever help they can, often in the form
of food or drinks.

I came with a tent packed for days that I'd sleep outside. I hoped for about a
50/50 split between that and staying in inns. When you're walking the pilgrimage
route it's basically impossible to plan ahead of time (re: reservations), since
you don't know how far you'll get each day. There's a lot of playing it by ear.

Temples generally don't close their gates, but the temple offices where you
receive proof of passage open at 8 a.m. So no matter how quickly you arrive
there in the morning, you can't continue until past 8. Hence it's part of a
walker's strategy to position the previous night's lodging about 2 hours away
from the next temple. You start walking at 6, get there just before 8, do the
rites, and you're on your way with no time loss.

Original Japanese:

不安と考え事で零時過ぎまで寝れなかった。金剛杖の丈夫さの心配もあったが朝起きて改
めて見ると他の人のとさほど変わらん。

朝食はお接待で遍路ハウスで頂いた。出発したらまず大麻比古神社に寄った。朝の七時で
も管理の人が優しく麻でできたお守を売ってくれた。なぜか泣いた。

極楽寺は綺麗だった。金泉寺は来た事がある気がしてならんかった。大日寺で二人のおじ
さんに飴を上げた。待っていると、台湾の Jeffery が現れても高原さんが中々来ず心配
した。地蔵寺で丁度お昼になってお弁当を売っているおばさんから買って食べた。安楽寺
まで行くとまた Jeffery と鉢合わせして今夜の野宿計画を立てた。まず十楽寺まで行っ
てお詣りしていると、ハワイ在住のアメリカ人女性と話した。 Pretty cute だった。宿
坊の予約がなかったから地図を見せて先の遍路小屋に送った。また会うだろう。夜は六番
の山門の上の鐘楼で寝る。戻ったら奇跡的に高原さんも居て、昼はさんざん迷ったと言う。
鐘楼にもう一人先客の「けんじさん」も居る。

お接待：朝食・蝋燭・線香・金剛杖の帽子・卵と水・チョコ

** Day 2 - April 17 (21km)

The ceaseless bombardment from mosquitos and the cement floor of the bell tower
meant I didn't manage much sleep. I gave up at 5 a.m. and hit the road alone.
Sydney wasn't at the Hut nor Kumadaniji (8), so I guess she got lost somewhere.
I saw Takahara-san again at temples 8 and 9. We were surrounded by farmers
fields; it was stereotypical Japanese countryside. Kirihataji (10) was up a
short mountainside, and it felt good to be surrounded by trees again. At a
nearby shop I finally picked up a Sugegasa that would actually fit my head.

Lunch was the biggest bowl of Udon I've eaten in my life. Turns out walking all
day makes you hungry.

By the late afternoon I had reached Fujiidera (11) and stayed the night at
pilgrim-specific placed called Yado Eleven. It seemed rather new and is close to
the foot of the mountain. Tomorrow is a big climb, the first real test for
walking pilgrims.

As a side note, walking alone is much more freeing.

Animals: 4 cats

Osettai: Water, candy, luggage storage, tea, use of a bicycle, a plastic bag.

Post-trip Addendum:

I didn't see Sydney again and have no idea where she could have gone. Jeffery
was also with me at Yado Eleven, and Kenji-san stayed outside. The three of us
had walked together most of the day. Kenji-san and I had dinner together at a
nearby cheap sushi place, but I didn't enjoy spending time with him.

Original Japanese:

蚊の絶えない攻撃と中々 comfortable になれん鐘楼の床でほぼ寝れなかった。五時に諦
めて一人で旅立った。 Sydney は八番の小屋の近くにおらず熊谷寺にも居なかったからお
そらく迷った。八番と九番でまた高原さんと会った。その辺りは畑ばかりで田舎の象徴。
切幡寺は一気に自然に戻り、近くの販売店で菅笠をやっと手に入れた。お昼はがっつりと
したざるうどんセット。夜はおやどイレブン、やたら新しく出来た、藤井寺のすぐ近くに
位置する宿。明日は登山。別件、独りで歩く方がやはり自由。

動物：猫４

お接待：水・菓子・荷物の置き場・お茶・自転車の使用・ビニール袋

** Day 3 - April 18 (28km)

I set off at around 5:40. I slept like a log last night. Breaks included, the
climb up to Shōsanji (12) took about 5.5 hours. At Jōren-an I swapped addresses
with Takahara-san; I have the feeling I won't see him again.

I took a longer lunch break and let the others go on ahead. Though hours later I
ran into them again at the foot of the mountain. Kenji-san will be staying at a
hut nearby while the other three of us pressed on to a campsite another hour or
so down the road. A lot of people were nice to us along the way. Tonight my tent
is pitched by a river. It's peaceful here.

Animals: 3 cats, 1 boar(?)

Osettai: Vitamins, a woman washed my cucumbers, water, citrus fruit, words of encouragement.

Post-trip Addendum:

The hike up Shōsanji is quite steep and is the first place that gives pilgrims
real trouble. Apparently a lot of people quit the journey here. It was peaceful
at the top and the air was quite cool. Looking back, that was the most intense
raw hike experience on the trip, probably because it was only the 3rd day and I
wasn't as strong yet. I remember seeing lights in my eyes as I got to the top. I
really had to push myself in some places.

As I thought, I didn't end up seeing Takahara-san again after that day, although
I heard later that he did make it up Shōsanji (reminder: 80 years old) and
continued his journey. As far as I know, he made it as far as he had planned,
about halfway.

I said "the three of us" after Kenji-san stayed behind, since a girl from France
named Barbara had joined up with us during the morning. It was myself, Jeffery,
and her at that campsite that night.

For a long time after this, whenever I was feeling tired or daunted by a
mountain climb or long stretch of road, I'd ask "Is this harder than Shōsanji?"
and the answer was always no. So on I went.

Original Japanese:

五時四十分出発。夜は快眠で爆睡。焼山寺は休憩を入れて五時間半ぐらい掛かった。浄蓮
庵で高原さんと住所を交換した。もう会わない気がする。お昼の休憩を長目に取って他の
人とはぐれた。が、その何時間後にまた阿野町で会った。けんじさんはそこで泊まり残っ
た我々三人は先のキャンプ場に進んだ。途中で親切にしてくれた人は何人か居た。今夜は
川端で寝る。

動物：猫３・猪１

お接待：ビタミン・キューリを洗ってもらった・炭酸水・柑橘類・頑張れとの励ましの声掛け

** Day 4 - April 19 (30km)

A strong wind had blown overnight and the air was cool so close to the river.
Once again I woke up around 5 and was gone after 40 minutes of cleanup and
preparations. As I walked, the morning light reflecting off the tree leaves made
me feel the beauty of reality.

It was about 5km to Dainichiji (13) and I arrived around 7:15. As I was waiting
for the Nōkyō Office to open, Kenji-san appeared. I found the timing strange and
he admitted he had set off at 4 that morning.

I continued on through the morning's temples, and stopped once at Temple 17 to
form a plan for the evening. The Shukubō of Tatsueji (19) was full, so instead I
called an inn called "Minshuku Chiba" nearby Temple 18 and booked a room there.
Unfortunately, it was another 20km further from where I was, and it was already
noon.

I lost about 1km in Tokushima City getting turned around the winding streets,
but in the end I made it to the inn just before 5. The road had been long and
hot, but I made it. Who knew what the human mind-body was capable of. Somehow
Barbara also showed up at Chiba later that evening. Jeffery had apparently
headed into the city proper and must have stayed somewhere there.

Animals: 2 cats

Osettai: Advice

Post-trip Addendum:

"Shukubō" are official accomodations within a temple, including meals. I had
very poor Shukubō luck this trip, only managing a single night's stay over the
47 days, and only because it was up a mountain and off the main pilgrim path at
a secondary temple. Worth it though.

Today was the last time I saw Kenji-san.

Original Japanese:

夜は涼しく風が強く吹いていた。また五時起きで約四十分で片付けと準備が出来て一人で
出発した。朝日が反射して来る木々の葉っぱは綺麗で現実を感じた。

大日寺まで約五粁、七時十五分頃に着いた。納経所が開くのを待っていると、けんじさん
が姿を現す。四時に出発したと言う。そうやって七番目まで行き、そこで夜の計画を立て
た。十九番の立江寺の宿坊は空きがないと言うので十八番の近くの「民宿ちば」に電話で
予約を入れた。距離はこの先二十粁。

一回徳島市内で迷って一粁位は損したけれど結局十七時ちょっと前にに到着した。道は長
くて暑かったがまた歩けた。人間はすごい。Barbaraも夕方、ちばに現れた。

動物：猫２

お接待：夜の相談・落とし物の届け・この先のアドバイス

** Day 5 - April 20 (20km)

"You're telling me these people have completed the route over 100 times? How on
earth is that possible?"

The inn owner's answer was simple: "By car."

From the other side of the room an older, veteran Henro pilgrim spoke up.
"That's not true Henro, that's little more than stamp collecting." He meant it.
At the time I thought him just a gruff old guy from the countryside, but later
in day at a temple he taught me how to do the cleansing ritual properly, and how
to better carry my Sanya Bag so it would balance out the weight better.

I quite liked Tatsueji (19). The monk at the Nōkyō Office told me a lot about
his training when I asked. He had spent 8 years atop Kōyasan, and finally came
back to Shikoku as this was his first master's temple.

Kakurinji (20) was up another mountain and was quite peaceful. The climb was
steep. The temple staff told me that I'd be able to sleep at an abandoned
elementary school in the village at the foot of the mountain. Just as I got down
and reached the school, it started to rain. Tonight I've pitched my tent under
the eaves of the gymnasium, with many swallow nests overhead. This school was
founded over 100 years ago, but at the moment is "not in use".

Animals: 1 cat, 2 mountain birds, 1 murder hornet

Post-trip Addendum:

A Sanya Bag is white and holds one's pilgrimage supplies, like the map,
candles and incense, prayer beads, etc. It's to be worn hanging in front, not
over the shoulder as I had been doing. Apart from this I also had my proper
hiking backpack of course, which weighed between 9 and 11kg depending on my
supplies of food and water that day.

The school being "out of service" is a growing trend in Japan, as economic
prosperity since the end of WW2 has spurred new opportunity and incentivised the
younger generations to flock to the cities. With fewer and fewer children in the
distant country towns, schools eventually close, which seals the loop. With no
schools, new families can't take up there, and the fate of the town is sealed.

I saw Barbara for the last time briefly at Tatsueji.

Original Japanese:

「１００回なんてどうやって廻るんですか」とちばの店主に訊くと「車だよ」と。横から
老練のお遍路さんが「それは遍路じゃなくて札攻めと云うんだよ」と批判の口で言った。
尖った田舎のおじさんとその時思ったら、後で道中で色々教えてくれた。身の清め方とさ
んや袋の背負い方。

立江寺は好きだった。納経所の和尚さんが彼の修行について色々語ってもらった。鶴林寺
も山の上で静寂だった。下の村の廃校に辿り着いた途端に雨が降り出した。今夜は燕の巣
が沢山ある屋根の下でテントを張って寝る。この学校は百年以上やっていたらしいが現在
「休校中」。

動物：猫１・山鳥２・雀蜂１

** Day 6 - April 21 (23km)

I wasn't eaten by the ghosts of lost children during the night. Barbara didn't
show up at the school, nor was she at Tairyūji (21), so I have no clue how far
she walked yesterday or where she ended up sleeping.

Today was another mountain climb, and it was absolutely worth it. Tairyūji is
also called "The Kōya of the West" and I found it quite serene and magical. I
got there before 8 and the entire place was enveloped in fog. There was no one
else around. Once the office opened, I bought a few gifts and a small
Kūkai-specific prayer bead bracelet for my wrist. Once back on the Henro trail,
you soon come to a place where Kūkai is said to have trained in his youth. Now,
atop a boulder overlooking the surrounding countryside, is a large seated statue
of him. Unfortunately due to the fog I couldn't see anything, but we had a good
chat. After promising to meet again, I continued on.

The path through the mountains was utterly silent. Partway through I passed by a
pilgrim walking in the opposite temple order and we wished each other luck.
Otherwise, there was nobody and nothing but me and the trees. After a few hours
I finally popped out into civilization and reached [[https://byodoji.online/en][Byōdōji]] (22). Once I'm back,
I definitely have to look this place up again. At the Nōkyō Office, they told me
about another abandoned school I could sleep at 2 hours further up the road.
Another chance for the ghosts, maybe.

Ah, and something I forgot to mention. As I had gotten through the mountains, it
started to pour. I had to pull out my rain gear for the first time, and it
performed wonderfully. I was especially pleased with my boots and socks; not wet
at all. At the moment I'm waiting out the rain in a Henro rest hut at Fukui
Elementary School. I'll sleep here tonight. Tomorrow I only plan to do a half
day in order to save my energy for the 3-day dash I'll soon be doing down the
coast.

Animals: 1 cat, 6 frogs, 5 mountain crabs, 1 murder hornet

Post-trip Addendum:

At [[https://byodoji.online/en][Byōdōji]] I was told that the old abbot's son recently took over, and has since
released a website, phone app, and streaming videos of their rituals and
services. Like, how many Buddhist monks can you picture [[https://www.twitch.tv/byodoji][Twitch streaming]] their
Flame Rituals? At least these guys are!

Original Japanese:

Barbaraは大井小にも太龍寺にも居なかったので一体どこまで歩いてどこで寝たかは想像
付かん。今日はまた朝から登山だった。しかしとても登る価値はあった。「西の高野」の
太龍寺は神秘的だった。丁度霧が掛かっていてほぼ誰も居なかった。いくつかの土産も買っ
た。寺から遍路道に進むと、空海が修行したと三教指帰に書いてある場所に来る。今は彼
の像が岩の上に背を向けて座っている。普段いい景色だろうが霧で麓の事何も見えない。
また会う約束をしてそこを後にした。

静かな参道だった。途中で逆打ちの人と会ったが他に数粁、何もなかった。数時間したら
やっと町に出て平等寺を訪れた。帰ったらまたここを調べるべし！納経所でまた訊いたら、
二時間位歩けばまた廃校で泊まれると云う。

あ、書き忘れたのは、登山という困難を乗り越えたら今度雨が降り出した。初めて雨具を
試して、ばっちり。特に靴と靴下が濡れなかったのが嬉しかった。今福井小学校の休憩所
で雨宿り。今夜ここで寝る。明日は半日だけ歩いて、明後日の三日連続ダッシュの為に力
を蓄える。

動物：猫１・蛙６・山蟹５・雀蜂１

** Day 7 - April 22 (16km)

Wide awake at 4:30. As usual, there's no one else around. I ate everything I
had, including my emergency Calorie Mate, and headed off. The town of Hiwasa and
the last temple of Tokushima, Yakuōji (23), are about a 4.5 hour walk away.

I first passed through the small coastal fishing town of Yuki. I wandered over
to the harbour and sat next to the nearest drink machine I could find, sipping
some canned coffee and resting my tight shoulder. The harbour cats roamed for
scraps. An old lady wandered by and we chatted for 20 minutes or so about the
town and its future. She said that while there's still an elementary school,
there's nobody left to take over the rice fields; the generation that should
have moved to the city instead. Apparently Hiwasa is still better off.

She was right, Hiwasa had much more going for it. I imagine that's in no small
part thanks to the train station and the temple atop the hill, Yakuōji. As I
finished my pilgrim's routine within the temple, who shows up from the dead but
Jeffery. Apparently he hit temples 20, 21, and 22 in a single day, which is
quite the load of mountain climbing. He opted to continue on from Hiwasa, while
I'm resting here for the rest of the day. Tomorrow I begin the 3-day journey to
Muroto.

Animals: 6 Harbour Cats

Post-trip Addendum:

That was the last I saw Jeffery in person. He ended up finishing the 88-temple
pilgrimage a full 10 days earlier than me, in 36 days. That's considered quite
fast, and he could only have done so by /averaging/ 30km per day, which
essentially means walking hard every day and never taking a day off. For
comparison, my daily average over this first week was ~22km. He later messaged
me that he wished he had taken his time a bit more and enjoyed the sights. I
honestly don't know how he didn't wreck his feet.

The gap between temples 23 and 24 is about 80km and typically takes 3 days to
walk. It's a walking pilgrim's second test. But at the end is Muroto Cape, where
Kūkai is said to have reached enlightenment.

Original Japanese:

四時半頃に起きた。相変わらず誰も居ない。非常食の Calorie Mate まで食べて片付けて
出発。四時間位歩けば薬王寺のある日和佐に辿り着くはず。

由岐と云う漁の町に出ると、まず港に向かい休憩を取った。コーヒーを飲んでいると地元
のお婆ちゃんが寄って来て二十分程町の事を話してくれた。小学校はまだあるが漁が減っ
ているし田んぼの後継ぎは都会に行ってしまっている。日和佐の方はまだましらしい。

その日和佐に着いて薬王寺でお参りを済ませたら Jeffery が現れた。２０、２１、２２
を一日で廻ったと言う。相当な登山だな！彼は先へ進み、俺は今日この町で少しゆっくり
する。明日から三日で室戸まで歩く。

動物：浜猫６

** Day 8 - April 23 (31km)

I was on the road by 5:15. It wasn't quite raining then, but started soon and
didn't stop all day. My rain gear held out and kept my body dry. However, 8
hours of exposure was more than enough to soak my backpack's rain bag through,
and the contents were a bit wet. My sleeping bag was absolutely waterlogged.
Aren't I glad I saved 72 grams but not bringing its own protective bag along?

Along the way I passed by Saba-Taishi (Bekkaku 4). Despite being a Bekkaku, it
was splendid enough to rival any of the nicer official 88 temples I had seen so
far. It had a "Kannon Cave" as well, with a Gomadō at its core where a
[[https://en.wikipedia.org/wiki/Acala][Fudō-Myō-ō]] is venerated. The staff in the Nōkyō office helped me pick a lodge
for the evening, and an older man who must have been the Abbot gave me some
canned green tea for the road. Their [[https://en.wikipedia.org/wiki/Shingon_Buddhism#Goma_fire_ritual][Goma rituals]] are every Sunday at 10:00, and
I'd definitely like to come back at some point.

From there it was 3 hours to the surf shack. The owner is a former pro surfer in
his late 60s, and his wife - apparently his second - is much younger than he is.
They have a 1-year-old named Shiki. For dinner they offered some Anroku, which
is a very rare form of seaweed that can only be harvested during a 10-day period
each year, a period which happens to be right now. Lucky me! It was really quite
good, and turns an interesting shade of light green with only a second or so of
exposure to boiling water.

Animals: 12 cats

Post-trip Addendum:

The "Bekkaku" (lit. different level) temples are 20 extra temples along the
route, not included in the original 88. However, 88 + 20 = 108, the number of
human "worries" named by Buddhism, and this gives them semi-special status. But
since they're not in the main 88 and are sometimes out of the way, they often
get fewer pilgrims. That said, I found them splendid in their own right. They
also sell a unique prayer bead with their temple's name engraved on it - collect
all 20 and you can form a full [[https://en.wikipedia.org/wiki/Buddhist_prayer_beads][Juzu]]! I hadn't got to the first 3 Bekkaku, but
once I picked up the bead at the 4th I was hooked. I ended up taking the extra
time to visit the rest, except 1, 2, 3, and 20. Next time.

Original Japanese:

五時十五分出発。一日中雨に降られた。雨具は基本的に優秀、体は濡れない。只リュック
は流石に八時間降られると袋に入っていても中身が少し濡れる。寝袋がびしょびしょ。

いずれ鯖大師と云う別格のお寺に来た。別格と云う割に綺麗で上位に入る。観音洞もあり、
その奥に不動明王が祀られている護摩堂があった。納経所の者も宿の相談してくれて住職
らしき人がお茶の缶をくれた。護摩会は毎週日曜日の朝十時で是非また来たい。

そこから三時間位歩いて今日の宿、波流月に着いた。店主は六十後半の元プロ Surfer 、
とその奥さんが二人目らしくめちゃくちゃ若い。一歳の娘が居て「四季」と云う。「安徳
布」（あんろく）と云う、本当にこの十日間位しか獲れない珍しい海藻を食べさせてくれ
た。

動物：猫１２

* Kōchi Prefecture - The Long Coast

** Day 9 - April 24 (24km)

I slept well. My sleeping bag, which should have dried over night hanging where
it was, had somehow gotten even wetter from the damp air. Once breakfast was
over, the owner drove me back up to Kaifu to dry my things at a Laundromat. Once
we got back, I set off right away. It was already 8. It was raining as hard as
yesterday, so on I went.

At Shishikui I finally found an available barber. Seriously: middle of the day,
middle of the countryside, a weekday, yet 5 barbers in a row were filled with
old folks cutting hair for other old folks. Once in the chair we had a good
chat. Apparently a good number of pilgrims stop by his place, especially since
it's directly on the pilgrimage route. About an hour after I left his place, he
appeared out of the blue in his car with some baked goods for me. I thanked him
while wondering who was watching the shop.

I hid from the rain for about half an hour at Meitokuji, a small temple not part
of the main 88 but on the map nonetheless. No one seemed to be home. After that
it was just a matter of trudging through the rain until I reached my destination
for the night around 15:30, a small roofed hut on the side of the highway. It
was right by the ocean with nothing before or after it for a good stretch.
Tomorrow is a 30km day. Unfortunately, the Shukubō at the cape's temple is
already full.

Animals: 1 monkey

Osettai: a ride to the laundromat, bread, more bread

Original Japanese:

よく寝た。夜中乾くはずの寝袋はむしろ更に濡れ、朝ご飯が終わると店主が海部にあるコ
インランドリーに連れて行ってくれた。ゲストハウスに戻るなりすぐに出発した。もう八
時だ。雨は昨日より弱目なので先へ進む。

宍喰でやっと空いているとこやが見つかり、話していると、お遍路さんがよく寄ると言う。
梅森さん。宿の相談もしてくれて、出た一時間後に急に車で現れてパンをくれた。

三十分程明徳寺で雨宿りしたが寺の人は誰も居なかった。そこから単に先へ進み今日の終
点、入木前の東屋に到着。海がすぐそこ。明日は三十粁の日。岬の宿坊は満室。

動物：猿１

お接待：送迎・パン・もっとパン

** Day 10 - April 25 (28km)

There was no Tsunami to wash me away during the night, but the inside of my tent
was still a bit damp when I awoke. And apparently, unlike lakes, the ocean
doesn't calm down at night. Or at least around here it doesn't.
Regardless, I wiped down the inside of the tent and dried out the fly a bit
before leaving around 6:00. Unlike the past two days, the sky was clear of clouds.

An older married couple made me lunch half an hour earlier than their usual
opening time. Apparently their granddaughter had spent some time in Canada.

At the cape, the view from the cliff-side lighthouse was fantastic. Deep, clear
blues from both the sky and sea. The temple, on the other hand, was fairly
plain. Since their Shukubō was full, I headed back down the mountain to a cheap
inn called "Kawasaki", where the owner was, shall we say, quite "honest" in her
speech. She kindly informed me how much I stank and promptly drew a bath for me.
There had been some mixup with my reservation (being forgotten), but it all
turned out in the end.

Animals: 6 cats, 1 murder hornet

Post-trip Addendum:

At the temple I ran into Tomatsu-san again, an actual monk walking the
pilgrimage in the traditional robes. I had met him the first time a day or two
previously near the town of Mugi as we were both being poured on by the sky. He
was trying to avoid inns as much as possible, which I assume is part of the
training. Sophie was at the temple too, a french woman who I had also briefly
met at Yakuōji (23) three days before.

Original Japanese:

どうやら津波は来なかったが起きた時にテント内は若干湿ってた。それと、海と云うのは
湖と違って夜になると静まる事はない。それかせめてここでは。ま、テントを拭いて乾か
して極力早く出発した。六時頃だった。今日は見事に晴れた。昼食は営業時間のいつもより３０分早
いと云うのに出してくれた夫婦が居て、孫がカナダに居たと言う。

岬の灯台から見た景色は素晴らしかった。寺の方は逆に普通だった。宿坊に入れないので
山から降りて、奥さんが正直者の「民宿川崎」で一泊。予約はどうやら忘れられたか、結
局泊まれたので結果的に良い。

動物：猫６・雀蜂１

** Day 11 - April 26 (25km)

I was up before 5:00 and out the door soon after. I didn't really want to
interact with the owner anymore, and didn't have to since it was so early. The
temple wasn't actually that far, so after scoping out its location I went and
grabbed breakfast at a convenience store. After completing the temple routine, I
killed some time reading a book while waiting for the Nōkyō office to open.

The climb up to Kongōchōji (26) wasn't bad at all. After that it was just
another long walk. Hours later, just short of my lodging for the night, it
decided to start drizzling. The town, Nahari, was otherwise nice.

You'd think my feet would be impervious by this point, but a blister on my right
heel has suddenly worsened and walking is becoming painful. I think tomorrow is
going to be a rest day, just in case.

Animals: 1 cat

Osettai: Mochi, gum, tea

Post-trip Addendum:

I was actually worried that I would have some critical foot issue and would have
to halt the pilgrimage, but that never happened. By this point I was used to
dealing with blisters, so I was surprised at this one. As a full-time walker,
you have no choice but to drain blisters when they form. I always did so with
scissors from my multitool, some disinfectant, and bandages. This nasty guy
required a somewhat deep cut to get at the liquid, and what came out was an
oddly red-tinged yellow (and a good amount of it). Fortunately, that was the
second last blister of the entire route.

I haven't mentioned food much, but breakfasts at convenience stores were a
fairly regular occurance. What else is open that early?

Original Japanese:

五時前に起きてすぐに出た。寺は比較的近かった為、まずコンビニに寄って朝食を済ませ
た。それから本を読みながら寺の納経所の前で時間を潰した。

金剛頂寺までの登山もつらくなかった。それから只長い歩きだった。宿に近づいたら丁度
雨が軽く降ってきた。奈半利は良い町だ。なぜか右足のマメが悪化して明日また休息日を
取ろうかなと考え中。

動物：猫１

お接待：餅・ガム・茶
