#+TITLE: The Henro Pilgrimage
#+DATE: 2024-06-04
#+AUTHOR: Colin
#+CATEGORY: buddhism

From 2024 April 16th to June 1st I walked 1265 kilometers around the island of
Shikoku in Japan. The route is called the [[https://en.wikipedia.org/wiki/Shikoku_Pilgrimage][Henro Pilgrimage]] and has existed in
evolving forms for perhaps 800 years. It is based on [[https://en.wikipedia.org/wiki/Shingon_Buddhism][Shingon Buddhism]] and
involves visiting 88 temples, offering rites and receiving various marks of
passage.

The route took me 47 days, the last of which I spent climbing Koyasan in
Wakayama to report my success to [[https://en.wikipedia.org/wiki/K%C5%ABkai][Kūkai]], the monk who brought Shingon to Japan
from China in the 800s, and is said to be in a state of eternal meditation on
the mountaintop.

This article is a transcription and translation of my handwritten journal
entries.

* Tokushima Prefecture - The Beginning

** Day 0 - April 15

Apparently the Japanese word for "Leech" is "Hiru", which happens to overlap
with the word for "afternoon". I've already been to Temple 1, Ryōzenji, with
Takahara-san, an 80-year-old man that is staying at the same Henro House lodge
as me today. I've already bought all the gear I need except for a [[https://en.wikipedia.org/wiki/Kasa_(hat)][Sugegasa]]. My
official start is supposed to be tomorrow, but the guy running the lodge
suggested we get the first temple out of the way today (just 100m up the road)
so that we can get on our way earlier tomorrow. We took his advice but it was
still so sudden that a large part of me was having trouble believing the journey
had really begun. Tonight I'm sharing a room with Takahara-san.

Post-trip Addendum:

[[https://henrohouse.jp/en][Henro House]] is an alliance of inns that cater to walking pilgrims and
smartphone-savvy folks from overseas. You can check availability and book
directly online. Average cost for one night is around 3500 yen. Sometimes they
feed you but not always.

I say "shared a room" but it was massive and probably could have slept 10
people.

Original Japanese:

「蛭」は Leech らしい。遍路ハウスで知り合った高原さん（８０歳）と一緒に霊山寺に
お詣りした。菅笠以外は全部購入済み。正式な出発は明日のはずだったが宿の人に今日の
内にした方が朝早く旅立てると言われてそうしたけれど、急で気持ちが追いつかなかった。
夜は高原さんと相部屋。

** Day 1 - April 16 (19km)

I couldn't sleep until past midnight. Nerves and other thoughts swam through my
head. I was worried that my [[https://en.wikipedia.org/wiki/Kong%C5%8D-zue][Kongō Staff]] wouldn't last the trip, but I see now
that it's pretty much the same as everyone else has.

Breakfast was offered as /Osettai/ by the Henro House. After setting off I headed
up to [[https://en.wikipedia.org/wiki/%C5%8Casahiko_Shrine][Ōasa-Hiko Jinja]] to ask protection from the nature gods (even though this
is a Buddhist pilgrimage). It was 7 a.m. but there was already an attendent
around. He was quite nice and sold me a charm unique to their Shrine made of
hemp. Setting off again, I cried for some reason. I felt like I had a lot of
support behind me and felt new determination.

Gokurakuji (2) was quite beautiful, and I couldn't shake the feeling I had been
to Kinsenji (3) already last year. At Dainichiji (4) I gave some candies to a
pair of older pilgrims. As I was taking a break, I met a guy named Jeffery from
Taiwan, but I was concerned that Takahara-san hadn't shown up yet. It was noon
by the time I arrived at Jizōji (5), so I bought a bentō from a lady selling
them in the parking lot. At Anrakuji (6) I ran into Jeffery again and we
discussed where we'd be sleeping for the night. I got us permission to stay in
the bell tower above the main gate from the temple staff. First though he'd head
up the road to Jūrakuji (7) and do it early. While there I met an American girl
from Hawaii named Sydney. She was pretty cute. She had nowhere to stay that
night so I took out my Japanese map and showed her the location of an offical
Henro Hut nearby. I'll probably see her again.

Once back at Anrakuji, lo-and-behold, Takahara-san was standing at the entrance.
Apparently he had gotten quite lost in the afternoon, but was otherwise fine. He
soon set off for the next temple. We then found someone else in the Bell Tower,
a tatami maker from Kyōto named Kenji-san. It's the three of us here tonight.

Osettai: Breakfast, candles, incense, a handle cover for my staff, eggs and
water, chocolate.

Post-trip Addendum:

/Osettai/ is a pilgrim hospitality culture specific to Shikoku. The locals know
how hard the journey is, so they offer whatever help they can, often in the form
of food or drinks.

I came with a tent packed for days that I'd sleep outside. I hoped for about a
50/50 split between that and staying in inns. When you're walking the pilgrimage
route it's basically impossible to plan ahead of time (re: reservations), since
you don't know how far you'll get each day. There's a lot of playing it by ear.

Temples generally don't close their gates, but the temple offices where you
receive proof of passage open at 8 a.m. So no matter how quickly you arrive
there in the morning, you can't continue until past 8. Hence it's part of a
walker's strategy to position the previous night's lodging about 2 hours away
from the next temple. You start walking at 6, get there just before 8, do the
rites, and you're on your way with no time loss.

Original Japanese:

不安と考え事で零時過ぎまで寝れなかった。金剛杖の丈夫さの心配もあったが朝起きて改
めて見ると他の人のとさほど変わらん。

朝食はお接待で遍路ハウスで頂いた。出発したらまず大麻比古神社に寄った。朝の七時で
も管理の人が優しく麻でできたお守を売ってくれた。なぜか泣いた。

極楽寺は綺麗だった。金泉寺は来た事がある気がしてならんかった。大日寺で二人のおじ
さんに飴を上げた。待っていると、台湾の Jeffery が現れても高原さんが中々来ず心配
した。地蔵寺で丁度お昼になってお弁当を売っているおばさんから買って食べた。安楽寺
まで行くとまた Jeffery と鉢合わせして今夜の野宿計画を立てた。まず十楽寺まで行っ
てお詣りしていると、ハワイ在住のアメリカ人女性と話した。 Pretty cute だった。宿
坊の予約がなかったから地図を見せて先の遍路小屋に送った。また会うだろう。夜は六番
の山門の上の鐘楼で寝る。戻ったら奇跡的に高原さんも居て、昼はさんざん迷ったと言う。
鐘楼にもう一人先客の「けんじさん」も居る。

お接待：朝食・蝋燭・線香・金剛杖の帽子・卵と水・チョコ

** Day 2 - April 17 (21km)

The ceaseless bombardment from mosquitos and the cement floor of the bell tower
meant I didn't manage much sleep. I gave up at 5 a.m. and hit the road alone.
Sydney wasn't at the Hut nor Kumadaniji (8), so I guess she got lost somewhere.
I saw Takahara-san again at temples 8 and 9. We were surrounded by farmers
fields; it was stereotypical Japanese countryside. Kirihataji (10) was up a
short mountainside, and it felt good to be surrounded by trees again. At a
nearby shop I finally picked up a Sugegasa that would actually fit my head.

Lunch was the biggest bowl of Udon I've eaten in my life. Turns out walking all
day makes you hungry.

By the late afternoon I had reached Fujiidera (11) and stayed the night at
pilgrim-specific placed called Yado Eleven. It seemed rather new and is close to
the foot of the mountain. Tomorrow is a big climb, the first real test for
walking pilgrims.

As a side note, walking alone is much more freeing.

Animals: 4 cats

Osettai: Water, candy, luggage storage, tea, use of a bicycle, a plastic bag.

Post-trip Addendum:

I didn't see Sydney again and have no idea where she could have gone. Jeffery
was also with me at Yado Eleven, and Kenji-san stayed outside. The three of us
had walked together most of the day. Kenji-san and I had dinner together at a
nearby cheap sushi place, but I didn't enjoy spending time with him.

Original Japanese:

蚊の絶えない攻撃と中々 comfortable になれん鐘楼の床でほぼ寝れなかった。五時に諦
めて一人で旅立った。 Sydney は八番の小屋の近くにおらず熊谷寺にも居なかったからお
そらく迷った。八番と九番でまた高原さんと会った。その辺りは畑ばかりで田舎の象徴。
切幡寺は一気に自然に戻り、近くの販売店で菅笠をやっと手に入れた。お昼はがっつりと
したざるうどんセット。夜はおやどイレブン、やたら新しく出来た、藤井寺のすぐ近くに
位置する宿。明日は登山。別件、独りで歩く方がやはり自由。

動物：猫４

お接待：水・菓子・荷物の置き場・お茶・自転車の使用・ビニール袋

** Day 3 - April 18 (28km)

I set off at around 5:40. I slept like a log last night. Breaks included, the
climb up to Shōsanji (12) took about 5.5 hours. At Jōren-an I swapped addresses
with Takahara-san; I have the feeling I won't see him again.

I took a longer lunch break and let the others go on ahead. Though hours later I
ran into them again at the foot of the mountain. Kenji-san will be staying at a
hut nearby while the other three of us pressed on to a campsite another hour or
so down the road. A lot of people were nice to us along the way. Tonight my tent
is pitched by a river. It's peaceful here.

Animals: 3 cats, 1 boar(?)

Osettai: Vitamins, a woman washed my cucumbers, water, citrus fruit, words of encouragement.

Post-trip Addendum:

The hike up Shōsanji is quite steep and is the first place that gives pilgrims
real trouble. Apparently a lot of people quit the journey here. It was peaceful
at the top and the air was quite cool. Looking back, that was the most intense
raw hike experience on the trip, probably because it was only the 3rd day and I
wasn't as strong yet. I remember seeing lights in my eyes as I got to the top. I
really had to push myself in some places.

As I thought, I didn't end up seeing Takahara-san again after that day, although
I heard later that he did make it up Shōsanji (reminder: 80 years old) and
continued his journey. As far as I know, he made it as far as he had planned,
about halfway.

I said "the three of us" after Kenji-san stayed behind, since a girl from France
named Barbara had joined up with us during the morning. It was myself, Jeffery,
and her at that campsite that night.

For a long time after this, whenever I was feeling tired or daunted by a
mountain climb or long stretch of road, I'd ask "Is this harder than Shōsanji?"
and the answer was always no. So on I went.

Original Japanese:

五時四十分出発。夜は快眠で爆睡。焼山寺は休憩を入れて五時間半ぐらい掛かった。浄蓮
庵で高原さんと住所を交換した。もう会わない気がする。お昼の休憩を長目に取って他の
人とはぐれた。が、その何時間後にまた阿野町で会った。けんじさんはそこで泊まり残っ
た我々三人は先のキャンプ場に進んだ。途中で親切にしてくれた人は何人か居た。今夜は
川端で寝る。

動物：猫３・猪１

お接待：ビタミン・キューリを洗ってもらった・炭酸水・柑橘類・頑張れとの励ましの声
掛け
