#+TITLE: NixとDanteでHaskell開発
#+DATE: 2018-01-10
#+AUTHOR: こりん
#+UPDATED: 2020-06-30
#+CATEGORY: haskell

*注意：* ２０２０現在、Haskell開発にはNixがあまりに複雑でもはや勧めません。
下記は元々２０１８年に書いたままです。

---

日頃のHaskell開発で使ってみるために（やっと）Nixを身につけました。下記は私のNix
設定と開発の流れの説明です。

* 最初の設定

ディストロはArch Linuxなので、最初はAURの ~nix~ パッケージをインストールしてみま
したが、どうやらnix環境がちゃんとできあがりませんでした。 [[https://nixos.org/nix/][nixos.org]]からの [[https://nixos.org/nix/manual/#chap-quick-start][公式方
法]]は逆にほぼうまく行きました：

#+BEGIN_SRC bash
curl https://nixos.org/nix/install | sh
#+END_SRC

作られた ~/nix~ directoryのwrite許可を自分で正す必要もあるので注意して下さい。

Environment variablesを設定するscriptを確認するには：

#+BEGIN_SRC bash
less /home/colin/.nix-profile/etc/profile.d/nix.sh
#+END_SRC

このscriptはbashしか存在しないと思い込んでいて私はfishのユーザーで、少し自分で設
定を書く必要がありました。 ~/home/colin/.config/fish/config.fish~ に：

#+BEGIN_SRC fish
set -x PATH ... '/home/colin/.nix-profile/bin'

# Nix
set -x NIX_PATH 'nixpkgs=/home/colin/.nix-defexpr/channels/nixpkgs'
set -x NIX_SSL_CERT_FILE '/etc/ssl/certs/ca-certificates.crt'
#+END_SRC

最後の行はディストロによって異なるので、上で説明した ~nix.sh~ の中身で確認しておいて下さい。

* Haskellの詳細

Nixでのプロジェクト設定は一般的にどんな感じか解るには [[https://github.com/Gabriel439/haskell-nix][Gabriel GonzalesのNix初心者ガイド]](英語）はなかなか
いい資源だと思います。

下記は簡単なプロジェクト向き：benchmarksとprofilingがしたい一つのlibraryかプログ
ラムの場合です。TravisCIとの統合、Emacsでの使い方の説明も含めています。

** Nix設定の自動生成

プロジェクトの中で ~cabal2nix~ を使って、「nix expressions」を ~.cabal~ から作り出せます。
インストールするには：

#+BEGIN_SRC bash
nix-env -i cabal2nix
#+END_SRC

で、Nix設定を作り出しましょう：

#+BEGIN_SRC bash
cabal2nix . > default.nix
#+END_SRC

~.cabal~ が変わる度にこれを繰り返す必要があります。

むしろ ~hpack~ が好みであれば：

#+BEGIN_SRC bash
nix-env --install --attr nixpkgs.haskellPackages.hpack
#+END_SRC

と：

#+BEGIN_SRC bash
hpack && cabal2nix . > default.nix
#+END_SRC

または ~fish~ で：

#+BEGIN_SRC fish
hpack; cabal2nix . > default.nix
#+END_SRC

** Nix Shellでの開発

Nixでのプロジェクトは三つのファイルで完成します：

- ~default.nix~
- ~shell.nix~
- ~release.nix~

が、普通の開発で最初の二つだけが必要になってきます。~nix-shell~ を使えばプロジェ
クトだけのdependenciesが入ってくる秘密森みたいな環境ができあがります。中にはいつ
も通り ~cabal test~ と ~cabal bench~が使えて、他のプロジェクトのdependenciesなど
が邪魔して来ません。

プロジェクトに下記の内容の ~shell.nix~ ファイルを作れば ~nix-shell~ が利用できる
ようになります：

#+BEGIN_SRC nix
let nixpkgs = import <nixpkgs> {};
    orig = nixpkgs.pkgs.haskellPackages.callPackage ./default.nix {};
in (nixpkgs.pkgs.haskell.lib.doBenchmark orig).env
#+END_SRC

よく見ると、本プロジェクトに関係するファイルの名前などが一切参考されていない・・・
ということは、これと全く同じ内容のファイルをどのプロジェクトでも使える訳です。

注意： ~doBenchmark~ の部分がなければ、benchmarkのdependenciesがshellに含まれません。

** ~release.nix~ の定義

Travisの時と正式にパッケージをあるNix Storeにインストールしたい時に
必要です。例えばパッケージが「vectortiles」というと：

#+BEGIN_SRC nix
let
  config = {
    packageOverrides = pkgs: {
      haskellPackages = pkgs.haskellPackages.override {
        overrides = haskellPackagesNew: haskellPackagesOld: {
          vectortiles = haskellPackagesNew.callPackage ./default.nix { };
        };
      };
    };
  };

  pkgs =
    import <nixpkgs> { inherit config; };

in
  { vectortiles = pkgs.haskellPackages.vectortiles;
  }
#+END_SRC

もっと短いのもありますが、設定を [[https://github.com/Gabriel439/haskell-nix/blob/master/project1/README.md#changing-versions][より細かく変えたい時]]にこの形が便利です。

プロジェクトを丸ごとコンパイル：

#+BEGIN_SRC bash
nix-build release.nix
#+END_SRC

コンパイル方の細かい選択肢は [[https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/lib.nix][こちら]]。

** Profiling

具体的にコードのどこが遅かったりすると知りたい時にprofilingですね。
Nixでこれが結構楽な経験です。
まず ~/home/you/.config/nixpkgs/config.nix~ を新しく作り、この内容を入れましょう：

#+BEGIN_SRC nix
{
  packageOverrides = super: let self = super.pkgs; in
  {
    profiledHaskellPackages = self.haskellPackages.override {
      overrides = self: super: {
        mkDerivation = args: super.mkDerivation (args // {
          enableLibraryProfiling = true;
        });
      };
    };
  };
}
#+END_SRC

で、profileしたいプロジェクトで ~profiling-shell.nix~ を新しく：

#+BEGIN_SRC nix
let nixpkgs = import <nixpkgs> {};
    orig = nixpkgs.pkgs.profiledHaskellPackages.callPackage ./default.nix {};
in (nixpkgs.pkgs.haskell.lib.doBenchmark orig).env
#+END_SRC

普通の ~shell.nix~ と殆ど一緒ですね。ただ今回は先程書いた
~profiledHaskellPackages~ の部分も含めています。 ~nix-shell profiling-shell.nix~
をしてみると、profiling用のdependenciesが全てコンパイルし直されます。一回目では
かなり時間がかかります。

私が調べた限り、普通のNix Storeにあったdependenciesがまだ健在です。いつも通り
~nix-shell~ を使うとprofiling用のdependenciesは使われません。

注意： ~nix-collect-garbage -d~ をしない事！すると時間をかけてコンパイルしたprofiling用の
dependenciesが全部なくなってしまいます。

では何かをprofileしましょう・・・　作っているのはlibraryならbenchmarksの
executableで良いでしょう。その方法：

- ~-prof~ と ~-fprof-auto~ をbenchmarkのGHC optionsに追加
- ~default.nix~ を生成し直す
- Profiling shellに入る: ~nix-shell profiling-shell.nix~
- ~cabal configure --enable-library-profiling --enable-benchmarks~
- ~cabal build~
- ~dist/build/projname/projname-bench +RTS -p~
- できた ~projname-bench.prof~ の中身を見る

(上でprojnameは勿論、あなたが作っているプロジェクトの名前）

結果によるとコードを訂正したり、普通の ~nix-shell~ で開発を進められます。

* Emacsでの使用

~dante-mode~ は色々と助けてくれます。
プロジェクトに ~shell.nix~ と ~default.nix~ が確認されると自動的にDanteが発動します。
まずインストールしましょう。

** ~Dante~ をインストール

普通のEmacsなら [[https://github.com/jyp/dante#installation][こちら]]。

Spacemacs（の ~develop~ branch!）のユーザーだと、そのままDanteが使えます。
~.spacemacs~ でHaskell Layerをこう設定しましょう：

#+BEGIN_SRC lisp
  (haskell :variables haskell-completion-backend 'dante)
#+END_SRC

そして ~dotspacemacs/user-config~ にこれを追加：

#+BEGIN_SRC lisp
  (add-hook 'dante-mode-hook 'flycheck-mode)
#+END_SRC

これがないとDanteの機嫌が悪くなります。

DanteにREPLがありません。いつもの ~SPC m s b~ も何もしません。ある関数を試すには：

#+BEGIN_SRC haskell
  -- >>> foo 5
  foo :: Int -> String
  foo = show
#+END_SRC

コメントの所に ~SPC m s e~ したら、コードはこう変わります：

#+BEGIN_SRC haskell
  -- >>> foo 5
  -- "5"
  foo :: Int -> String
  foo = show
#+END_SRC

これさえできればDanteの論理によるとREPLが要らないそうです。

** Danteとtestsとbenchmarks

上の設定だけでDanteはtestのbenchmarkのファイルでちゃんと発動しません。
Emacsの「file-local variables」を使えばこの問題を避けられます。

~vectortiles~ というプロジェクトで ~Test.hs~ というファイルがあるとして、まず開いてみます。
~add-file-local-variable-prop-line~ というEmacs関数を使うと選択肢が出ます。
~dante-target~ を選んでこれを ~vectortiles-test~ (~.cabal~ の中との同じ名前)に設定すると、
ファイルの最初の行にこのコメントが現れます：

#+BEGIN_SRC haskell
  -- -*- dante-target: "vectortiles-test"; -*-
#+END_SRC

この後 ~Test.hs~ を開く度にDanteがちゃんと発動します。

* 継続的インテグレーション

やっぱりTravisが一番？

** Travis

[[https://docs.travis-ci.com/user/languages/nix/][公式の指示]]

結構簡単ですね。パッケージが ~vectortiles~ というと、この ~.travis.yml~ で十分：

#+BEGIN_SRC yaml
  sudo: true  # 「Docker抜き」。こうやった方がかなり速い。
  language: nix
  script: nix-build --attr vectortiles release.nix
#+END_SRC

期待通り、testが失敗するとCIも失敗します。Dependenciesが毎回ダウンロードされる割に
数分で終始するはずです。

~hpack~ も混ぜたかったらどうぞ：

#+BEGIN_SRC yaml
  sudo: true

  language: nix

  before_install: nix-env --install --attr nixpkgs.haskellPackages.hpack

  script:
    - hpack
    - nix-build --attr vectortiles release.nix
#+END_SRC

** Hercules

[[https://github.com/hercules-ci/hercules][Github repository]].

NixのためだけのCIシステム。かなり最新の物で、「1.0」が [[https://github.com/hercules-ci/hercules/issues/5][まだまだ遠いみたいらしいです]]。

** CircleCI

CircleCIではHaskellのCIは [[https://circleci.com/docs/1.0/language-haskell/][一応できます]]がNixは優先されていないようです。
一人ぐらいは [[https://discuss.circleci.com/t/caching-root-directory-nix-not-working/10626][頑張っているみたい]]ですが。

** Hydraを自分で

[[https://nixos.org/hydra/][公式サイト]]

Nixと言えば当たり前かもしれませんが、私みたいな平凡開発者には複雑すぎます。

* Stackとの比べ

「慣れているのと違う、諦めよう」などせずに、しばらくはNixとDanteで頑張ってみたかったです。
あるプロジェクトを丸ごとstackからNixに移してから、次のNix/Danteの長所が見えてきました：

- 普通開発の時も、CIの時も、Herokuなどに展開する時も、dependencyダウンロードの速さ
- Travis設定の簡単さ
- Haskellじゃないdependenciesの整理
- [[https://github.com/sol/doctest][doctest]]との協力。 Danteで作ったコメントがあれば：

#+BEGIN_SRC haskell
  -- | この関数は何とかこうとか。
  --
  -- >>> inc 1
  -- 2
  inc :: Int -> Int
  inc n = n + 1
#+END_SRC

このシンタックスも ~doctest~ に理解されて、関数の正当性の証明にもなります。
~inc~ が変わって証明が崩れると、何かの間違いにすぐ気づかされます。

そしてStack/Interoの長所：

- インストールの簡単さ（特に初心者にとって）
- プロジェクト設定の簡単さ（最小限、 ~stack.yaml~ は一つの行で十分）
- Nixより「コンパイルは絶対成功する」という保証が強い
- ~intero~ の設定は簡単で、Danteより機能が多い
- ~cabal~ にない ~stack~ の様々な機能：
  - File watchが便利すぎる: ~stack build --haddock-deps --test --file-watch --fast~
  - ~stack test~ と ~stack bench~ が短くて解りやすい
  - オフライン・ドキュメンテーション: ~stack haddock --open foobar~
  - Dependency graphs: ~stack dot --external --prune base,ghc-prim,integer-gmp,deepseq,array | dot -Tjpg -o deps.jpg~
  - ~stack upload .~

* 資源

- [[https://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure][NixのHaskellパッケージ公式ガイド]]
- [[https://github.com/Gabriel439/haskell-nix][Gabriel GonzalesのNix初心者ガイド]]
- [[http://vaibhavsagar.com/blog/2018/01/03/static-haskell-nix/][Building static Haskell binaries]]
- Emacsの [[https://github.com/jyp/dante][dante-mode]]
