name: bridge
version: '1.0.0'
synopsis: Convert Haskell types to Purescript types.
description: Convert Haskell types to Purescript types.
category: Web
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3
git: git://github.com/fosskers/fosskers.ca.git

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.8 && < 4.11
  - protolude >= 0.2 && < 0.3
  - servant-purescript >= 0.9 && < 0.10

executables:
  bridge:
    source-dirs: .
    main: Bridge.hs
