#+TITLE: ServantとPurescript/Halogenでウェブ開発
#+DATE: 2018-02-21
#+AUTHOR: こりん
#+UPDATED: 2020-06-18
#+CATEGORY: haskell

*注意：* この記事の内容は現在のPurescriptと一致していません。
ある程度の参考にはなるかもしれませんが、これを元にプロジェクトを始めないで下さい。

* Haskell

ウェブ・サーバーを開発する時はやはり [[http://haskell-servant.readthedocs.io/en/stable/][Servant]]。自分の経験ではどの言語のどのフレー
ムワークでも開発効率が一番高いと思います。幸い、Purescriptとの統合も簡単な事です。

このガイドを使うには「stack」と「Servant」の経験が必要です。

** プロジェクト設定

Purescriptとのコードシェアがうまくいく様にbackendを三つに分けることを勧めます。
それぞれの部分にはちゃんと ~.cabal~ または ~package.yaml~ を置きましょう。stack
設定は以下の様に：

#+BEGIN_SRC yaml
  resolver: lts-10.6  # ２０１８年2月現在

  packages:
    - lib      # Purescriptとシェアしたい全て。ServantのAPIタイプも含めて！
    - server   # Backendの本格的コード。
    - bridge   # `lib`を使ってPurescriptを生み出してくれるコード。

  extra-deps:
    - servant-0.12.1
    - servant-server-0.12
    - servant-foreign-0.10.2
#+END_SRC

** Purescriptとのコードシェア

二つのlibrariesが助けてくれます：

- ~purescript-bridge~: 指定したHaskellタイプと一致するPurescriptを生み出します。
- ~servant-purescript~: BackendのJSON endpointsが問えるPurescriptを生み出します。

どうやら ~servant-purescript~ はJSON endpointsでしか使えない様で、本サイトの
~Common~ module にはこういうのがあります：

#+BEGIN_SRC haskell
  type JsonAPI = "posts" :> Get '[JSON] [Blog]

  type API = JsonAPI
    :<|> "blog" :> Capture "post" Text :> Get '[HTML] (Html ())
    :<|> "assets" :> Raw
    :<|> "webfonts" :> Raw
    :<|> Get '[HTML] (Html ())
#+END_SRC

Purescriptとシェアしたいのは ~JsonAPI~ だけですので、 ~bridge~ のプログラムには：

#+BEGIN_SRC haskell
  {-# LANGUAGE DataKinds, FlexibleContexts #-}

  module Main where

  import Common (Blog, JsonAPI)
  import Language.PureScript.Bridge
  import Servant.PureScript
  import Time.Types

  -- | Purescriptにしたい自分のHaskellタイプ。新しいPurescriptが出る。
  types :: [SumType 'Haskell]
  types = [ mkSumType (Proxy :: Proxy Blog) ]

  -- | 自作「bridge」。形の全く同じHaskellとPurescriptのタイプを繋げたいと意味する。
  -- 新しいコードは出ない。ただJSON decodingの際にだけ使われる。
  monthBridge :: BridgePart
  monthBridge = typeName ^== "Month" >> pure psMonth

  psMonth :: PSType
  psMonth = TypeInfo { _typePackage    = "purescript-datetime"
                     , _typeModule     = "Data.Date"
                     , _typeName       = "Month"
                     , _typeParameters = [] }

  main :: IO ()
  main = do
    writePSTypes "site/src" (buildBridge $ defaultBridge <|> monthBridge) types
    writeAPIModule "site/src" defaultBridgeProxy (Proxy :: Proxy JsonAPI)
#+END_SRC

~stack exec -- bridge~ を使ってみると、 ~site/src~ に新しいPurescriptコードが現れます。
下記の「Halogen」の所にこのコードをどう使うかは説明されます。

** Assetsの提供

あるディレクトリーのファイルをそのまま提供するのは簡単です：

#+BEGIN_SRC haskell
  import Servant.Utils.StaticFiles (serveDirectoryFileServer)

  type API = ... :<|> "assets" :> Raw

  server :: Server API
  server = ... :<|> serveDirectoryFileServer "assets"
#+END_SRC

これでassets (~.js~ や ~.css~ のファイル)を全部 ~assets/~ に放り込めます。

*** 自動圧縮

少しコードを足すだけでサーバーから出されるAssetsの重さを数倍軽くしてくれる [[https://hackage.haskell.org/package/wai-extra][wai-extra]]：

#+BEGIN_SRC haskell
  import Network.Wai.Middleware.Gzip

  app :: Application
  app = gzip (def { gzipFiles = GzipCompress }) $ serve (Proxy :: Proxy API) server
  -- 元はこんな感じ：
  --   app = serve (Proxy :: Proxy API) server
#+END_SRC

** HTML無し

PurescriptがUIを管理するおかげでHTMLファイルをコミットする必要は実はありません。
~index.html~ さえbackendが出してくれます：

#+BEGIN_SRC haskell
  import Lucid
  import Servant.HTML.Lucid

  -- | この最後の`Get`がサイトの本（`/`）に一致する。
  type API = ... :<|> Get '[HTML] (Html ())

  index :: Html ()
  index = html_ $ head_ h *> body_ (script_ [src_ "assets/app.js"] ("" :: Text))
    where h = do
            title_ "fosskers.ca"
            link_ [ rel_ "stylesheet", href_ "assets/fosskers.css" ]

  server :: Server API
  server = ... :<|> pure index
#+END_SRC

* Purescript

** 最初の設定

[[https://www.npmjs.com/][npm]]をインストールしてから進む事。

*** ツール

もっとも扱いやすいPurescript開発環境を築くには ~npm~ を利用しないと。
これで ~package.json~ が生まれます：

#+BEGIN_SRC bash
  npm init
#+END_SRC

次はツールをインストールします。普段はディストロのpackage manager意外のを使うの
はあまり気に入りませんが、この場合は心配ありません。次のコマンドで必要のツールが
全部プロジェクト・ディレクトリー（ ~node-modules/~ の中）だけにインストールされ
ます：

#+BEGIN_SRC bash
  npm install purescript pulp psc-package pscid purescript-psa uglify-js --save-dev
#+END_SRC

- ~purescript~: コンパイラ
- ~pulp~: ~cabal~ みたいなbuild tool
- ~psc-package~: Purescript librariesのpackage manager
- ~pscid~: ~stack build --file-watch~ みたいなコンパイラ・デーモン
- ~purescript-psa~: ~pulp~ に使われてより解りやすいコンパイル・エラーを出す
- ~uglify-js~: Javascriptの圧縮のため

上のコマンドで ~package.json~ にもこのツールの名前が現れます。実際に使うに
は~package.json~ にこれを：

#+BEGIN_SRC js
  ...
  "scripts": {
      "pulp": "pulp --psc-package",
      "pscid": "pscid",
      "psc": "psc-package",
      "uglify": "uglifyjs"
  },
  ...
#+END_SRC

*** Purescriptパッケージ

上で開発に必要なツールだけがインストールされました。Purescriptのプロジェク設定や
コードらしきファイルがまだありません。作りましょう：

#+BEGIN_SRC bash
  npm run pulp init
#+END_SRC

これで作られるのは：

- ~psc-package.json~: Library Dependenciesを示す所
- ~src/Main.purs~
- ~test/Main.purs~

[[https://pursuit.purescript.org/][Pursuit]]ではありのPurescript Librariesを調べたりできます。インストールするのも楽です：

#+BEGIN_SRC bash
  # `purescript-halogen`というパッケージをインストールする。
  # 注意：`purescript-`の部分を除く事。
  npm run psc -- install halogen
#+END_SRC

ダウンロードされるバージョンは ~psc-package.json~ に設定される [[https://github.com/purescript/package-sets][psc・パッケージ・
セット]]のバージョンによって異なってきます。ダウンロードが成功したら ~halogen~ の
名前がdependencyとして ~psc-package.json~ に現れます。

*** Spacemacsでの使用

そのまま [[http://spacemacs.org/layers/+lang/purescript/README.html][PureScript Layer]]を使いましょう。 ~npm~ でインストールしたツールもちゃんと見つ
かる様にこう設定しましょう：

#+BEGIN_SRC lisp
  (purescript :variables psc-ide-use-npm-bin t)
#+END_SRC

下を ~dotspacemacs/user-config~ にも追加する必要があります：

#+BEGIN_SRC lisp
  (add-hook 'purescript-mode-hook 'flycheck-mode)
#+END_SRC

便利なKeybindings:

| キー          | 結果                           |
|---------------+--------------------------------|
| ~SPC m m s~   | ~pscid~ 発動                   |
| ~SPC m m i a~ | ~point~ にある関数を自動インポート |

** 便利なコマンド

~package.json~ にあるツールを全部（再）ダウンロード：

#+BEGIN_SRC bash
  npm install
#+END_SRC

~psc-package.json~ にあるlibrary dependenciesを全部（再）ダウンロード：

#+BEGIN_SRC bash
  npm run psc -- install
#+END_SRC

Librariesもプロジェクト・コードも全部コンパイル：

#+BEGIN_SRC bash
  npm run pulp build
#+END_SRC

コンパイラ・デーモンを発動：

#+BEGIN_SRC bash
  npm run pscid
#+END_SRC

テストの確認：

#+BEGIN_SRC bash
  npm run pulp test
#+END_SRC

必要なコードだけJavascriptに変える（いわゆる「dead code elimination」）：

#+BEGIN_SRC bash
  npm run pulp -- browserify --optimise --to app.js
#+END_SRC

~pulp build~ や ~pulp browserify~ で作られたJavascriptを更に圧縮：

#+BEGIN_SRC bash
  npm run uglify -- app.js --output min.js --compress --mangle
#+END_SRC

コードの長さは半分ぐらい減ります。

** Halogen

本格的に開発を始める前にHalogenの [[https://github.com/slamdata/purescript-halogen/tree/master/docs][公式ガイド]]（英語）を全部読みました。内容を理解した
ところで開発に必要な知識の9割ぐらい取って、残りは [[https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md][HaskellとPurescriptの区別]]を調
べたり試行錯誤したりして判りました。発見したことは次のように。

*** 無駄なレンダリングの回避

~eval~ の関数の中で ~H.put~ と ~H.modify~ が使われる度にそのコンポーネントが再レ
ンダリングされます。下のコードを使えばstateが本当に変わる時にだけ再レンダリング
が行われます：

#+BEGIN_SRC purescript
  -- | 変わった限りStateをアップデート。
  update :: forall s a m. MonadState s m => Eq a => Lens' s a -> a -> m Unit
  update l a = do
    curr <- gets (_ ^. l)
    unless (a == curr) $ modify (_ # l .~ a)
#+END_SRC

利用の例：

#+BEGIN_SRC purescript
  eval = case _ do
    NewKeywords kws next -> update (prop (SProxy :: SProxy "keywords")) kws *> pure next
    ...  -- more cases here
#+END_SRC

~prop~ の説明は [[https://pursuit.purescript.org/packages/purescript-profunctor-lenses/3.8.0/docs/Data.Lens.Record#v:prop][こちら]]。

*** ~servant-purescript~ が出したタイプや関数の扱い

~type JsonAPI = "posts" :> Get '[JSON] [Blog]~ から ~servant-purescript~ はこれを吐き出す：

#+BEGIN_SRC purescript
  getPosts :: forall eff m.
              MonadAsk (SPSettings_ SPParams_) m =>
              MonadError AjaxError m =>
              MonadAff ( ajax :: AJAX | eff ) m
              => m (Array Blog)
#+END_SRC

普段、コンポーネントの関数のEffect Monad Parameterは ~m~ で十分ですが、
~getPosts~を使うとすぐ ~MonadAsk~ と等が広がってしまいます。長くて判りづらいtype
signaturesと何回も同じインポートを繰り返すのを避けるために ~Types.purs~ にはこれ
を入れておきました：

#+BEGIN_SRC purescript
  type Effects eff = ReaderT (SPSettings_ SPParams_)
                     (ExceptT AjaxError (Aff (ajax :: AJAX, console :: CONSOLE, dom :: DOM | eff)))

  runEffects :: forall eff. Effects eff ~> Aff (ajax :: AJAX, console :: CONSOLE, dom :: DOM | eff)
  runEffects eff = runExceptT (runReaderT eff settings) >>= either (\e -> log (errorToString e) *> empty) pure

  settings :: SPSettings_ SPParams_
  settings = defaultSettings $ SPParams_ { baseURL: "/" }
#+END_SRC

そして他の関数のsignaturesはこう簡単に：

#+BEGIN_SRC purescript
  component :: forall e. H.Component HH.HTML Query Unit Void (Effects e)
#+END_SRC

~main~ を少しだけ ~hoist~ で支えると全部無事にコンパイルするはずです：

#+BEGIN_SRC purescript
  import Halogen.Aff as HA
  import Halogen.Component as HC

  main :: Eff (HA.HalogenEffects (ajax :: AJAX, console :: CONSOLE)) Unit
  main = HA.runHalogenAff do
    body <- HA.awaitBody
    runUI (HC.hoist runEffects Page.component) unit body
#+END_SRC

*** Effectのあるコンポーネント発動

サーバー等から情報がないと発動できないコンポーネントも時々あります。こういう場合、
普通の ~H.component~ （または ~H.parentComponent~ ）の代わりに
~H.lifecycleComponent~ が必要となってきます。

#+BEGIN_SRC purescript
  data Query a = ... | Initialize a

  -- `lifecycleParentComponent`もある。
  component :: forall e. H.Component HH.HTML Query Unit Void (Effects e)
  component = H.lifecycleComponent { initialState: const state
                                   , render
                                   , eval
                                   , receiver: const Nothing
                                   , initializer: Just $ Initialize unit
                                   , finalizer: Nothing }
    where state = ...

  eval :: forall e. Query ~> H.ComponentDSL State Query Void (Effects e)
  eval = case _ of
    ...  -- cases for other query terms.
    Initialize next -> do
      _ <- HQ.fork do
        posts <- H.lift getPosts
        H.modify (_ { posts = posts })
      pure next
#+END_SRC

注意： ~fork~ しないとリクエストが返るまで何も動きません！

*** HTMLの要求と注入

訳あって本サイトのブログのHTMLはruntimeにしか存在しません。記事を選んでクリック
したら一つのXHRだけがされて返事のHTMLはそのままページに注入されます。これを達成す
るには三つにlibraryが必要でした： ~affjax~ ・ ~domparser~ ・ ~dom-classy~

下のコードでサーバーへのHTML要求ができます：

#+BEGIN_SRC purescript
  -- | サーバーへHTML要求。
  xhr :: forall e. String -> Aff ( ajax :: AJAX, dom :: DOM | e ) (Array Node)
  xhr p = do
    res <- get $ "/blog/" <> p
    liftEff do
      parser <- newDOMParser
      let doc = parseHTMLFromString res.response parser
      body <- lastChild doc >>= (map join <<< traverse lastChild)
      maybe (pure []) children body

  replaceChildren :: forall e n m. IsNode n => IsNode m => n -> Array m -> Eff ( dom :: DOM | e ) Unit
  replaceChildren el news = removeChildren el *> traverse_ (\n -> appendChild n el) news

  removeChildren :: forall n e. IsNode n => n -> Eff ( dom :: DOM | e ) Unit
  removeChildren el = children el >>= traverse_ (\n -> removeChild n el)

  children :: forall n e. IsNode n => n -> Eff ( dom :: DOM | e ) (Array Node)
  children el = do
    kids <- childNodes el
    len  <- length kids
    let ixs = range 0 (len - 1)
    catMaybes <$> traverse (\i -> item i kids) ixs
#+END_SRC

~children~ などで ~halogen~ の管轄外で直接DOMを操れます。まずはプレースホルダー
の ~<div>~ を：

#+BEGIN_SRC purescript
  post :: forall c q. HH.HTML c q
  post = HH.div [ HP.ref (H.RefLabel "blogpost") ] []
#+END_SRC

もらったHTMLは後でここに入ります。 ~post~ 自体は勿論いつもの ~render~ 関数のどこ
かに入ます。大事なのは ~RefLabel~ 。実際内容を注ぎ込みたいと ~eval~ で：

#+BEGIN_SRC purescript
  eval :: forall e. Query ~> H.ComponentDSL State Query Void (Effects e)
  eval = case _ of
    ...  -- other cases
    Selected s next -> do
      curr <- H.gets _.selected
      unless (s == curr) $ do
        H.modify (_ { selected = s })
        htmls <- H.getHTMLElementRef (H.RefLabel "blogpost")
        traverse_ (\el -> liftAff (xhr s) >>= liftEff <<< replaceChildren el) htmls
      pure next
#+END_SRC
* Deployment

基本的にHaskellのデプロイメントとなれば「Heroku」を勧めます。 [[https://www.fosskers.ca/jp/blog/deploying-haskell][別のポスト]]に一般の
説明が書いてあります。それを読んだ上で ~heroku-buildpack-stack~ の仕組みを利用し
て「Purescript」も含めれます。

** ~Makefile~ の定義

幸い ~heroku-buildpack-stack~ のスクリプトがユーザーからの ~Makefile~ がないか
確認してから構築に入ります。ない場合はただ：

#+BEGIN_SRC bash
  stack build --copy-bins
#+END_SRC

あった場合は ~make~ と ~make install~ のコマンドが行われます。大体 ~make~ イコール ~bash~
なので、その事実を利用して ~npm~ や ~purescript~ dependenciesや全部ダウンロードして
もらいましょう：

#+BEGIN_SRC makefile
  default:
    stack build
    stack exec -- bridge
    wget --quiet https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-x64.tar.xz
    tar xf node-v8.9.4-linux-x64.tar.xz
    export PATH="/app/node-v8.9.4-linux-x64/bin:${PATH}" && cd site && \
      npm install && \
      npm run psc -- update && \
      npm run pulp -- build --to app.js && \
      npm run uglify -- app.js --output app.min.js --compress --mangle && \
      mkdir -p ../.local/bin/ && \
      cp app.min.js ../.local/bin/

  install:
    stack build --copy-bins
#+END_SRC

最後の辺、 ~app.min.js~ がコピーされるのがあります。理由はHerokuがデプロイを完成
した時、dynoに残るファイルは元々あったファイル（即ちgitに入っているファイル）と
構築中に ~/app/.local/bin~ に移動させられたファイルだけです（実行ファイルも。な
ので ~--copy-bins~ ）。サーバーに ~app.min.js~ が見つけられる様に ~assets/~ にソ
フトリンクをコミットすれば十分です：

#+BEGIN_SRC bash
  ln -s ../.local/bin/app.min.js app.min.js
#+END_SRC

そしてサーバーにはいつも通り ~/assets/app.min.js~ が出せるはずです。
