[env]
PORT = "8000"

[config]
skip_core_tasks = true

# ---- BASIC ----

[tasks.watch]
description = "Watch files and recompile the project on change"
run_task = [
    { name = "build" },
]
watch = true

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["--port", "${PORT}"]

# ---- BUILD ----

[tasks.build]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_release]
description = "Build with wasm-pack in release mode"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "love"]

[tasks.copy_wasm]
description = "Copy release-mode WASM to the top-level assets folder."
script = "cp pkg/love_bg.wasm ../../assets/"

[tasks.copy_js]
description = "Copy release-mode JS to the top-level assets folder."
script = "cp pkg/love.js ../../assets/"

[tasks.release]
dependencies = [
  "build_release",
  "copy_wasm",
  "copy_js"
]
