name: Rust

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Tools and Demos
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        uses: actions/checkout@v2.3.3

      - name: Game of Life
        run: |
          cd demos/game-of-life
          cargo build

      - name: Al Bhed
        run: |
          cd tools/al-bhed
          cargo build
